Basic work
Kicer86/aqua_driver pull request #4
Opened 2023-11-08 14:18 UTC by ThudPoland

Working on basic schematic elements

2023-11-11 20:18 UTC, Kicer86 commented
Please rebase on master

2023-11-11 20:20 UTC, Kicer86 requested changes
Please rebase

2023-11-13 20:16 UTC, ThudPoland commented
> Please rebase on master
Done

2023-11-13 21:05 UTC, Kicer86 approved these changes

2023-11-13 21:06 UTC, merged